import bcrypt from 'bcryptjs';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { mockAssessments } from '../src/data/mockAssessments';

/**
 * Seed mock login credentials, server-side only.
 *
 * PLACEHOLDER DECISION (per prompt section 6, not final): username = agent's Email (sheet column C).
 * For the two agents whose email isn't confirmed (David Thorpe — truncated domain; Joey wong — not
 * captured), a clearly-flagged placeholder username is generated instead so a login can still exist
 * for testing; real credentials must be re-issued once those emails are confirmed against the sheet.
 *
 * Passwords are randomly generated here and never stored in plaintext — only their bcrypt hash goes
 * into credentials.json. The plaintext is printed once and written to seed-credentials.txt (gitignored).
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function generatePassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
  let out = '';
  for (let i = 0; i < 10; i++) {
    out += chars[Math.floor(Math.random() * chars.length)];
  }
  return out;
}

async function seed() {
  const lines: string[] = [
    'FA Assessment Dashboard — mock login credentials (generated by server/seed.ts)',
    'MOCK PHASE ONLY. Do not reuse these passwords anywhere real.',
    '',
  ];
  const credentials: Array<{ agentId: string; username: string; passwordHash: string; placeholderUsername: boolean }> = [];

  for (const agent of mockAssessments) {
    const hasConfirmedEmail = !!agent.email && !agent.emailNote;
    const username = hasConfirmedEmail
      ? (agent.email as string)
      : `${agent.id}@todo-confirm-email.local`;
    const password = generatePassword();
    const passwordHash = await bcrypt.hash(password, 10);

    credentials.push({ agentId: agent.id, username, passwordHash, placeholderUsername: !hasConfirmedEmail });

    lines.push(`${agent.name}`);
    lines.push(`  username: ${username}${hasConfirmedEmail ? '' : '  [PLACEHOLDER — real email unconfirmed, see README]'}`);
    lines.push(`  password: ${password}`);
    lines.push('');
  }

  writeFileSync(path.join(__dirname, 'data', 'credentials.json'), JSON.stringify(credentials, null, 2));
  writeFileSync(path.join(__dirname, '..', 'seed-credentials.txt'), lines.join('\n'));

  console.log(lines.join('\n'));
  console.log(`Seeded ${credentials.length} agent accounts.`);
  console.log('Plaintext credentials written once to seed-credentials.txt (gitignored). Hashes only in server/data/credentials.json.');
}

seed();
