import bcrypt from 'bcryptjs';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { loadLiveAssessments } from './data/liveSource';

/**
 * Seed login credentials from the live-synced agent list, server-side only.
 *
 * PLACEHOLDER DECISION (per prompt section 6, still not final): username = agent's Email
 * (AssessmentDash column C, now sourced live). If an agent has no email on record, a clearly
 * flagged placeholder username is generated instead so a login can still exist for testing.
 *
 * Passwords are randomly generated here and never stored in plaintext — only their bcrypt hash
 * goes into credentials.json. The plaintext is printed once and written to seed-credentials.txt
 * (gitignored).
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function generatePassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
  let out = '';
  for (let i = 0; i < 10; i++) {
    out += chars[Math.floor(Math.random() * chars.length)];
  }
  return out;
}

async function seed() {
  const agents = await loadLiveAssessments();

  const lines: string[] = [
    'FA Assessment Dashboard — live login credentials (generated by server/seed.ts)',
    'Do not reuse these passwords anywhere else.',
    '',
  ];
  const credentials: Array<{ agentId: string; username: string; passwordHash: string; placeholderUsername: boolean }> = [];

  for (const agent of agents) {
    const hasEmail = !!agent.email;
    const username = hasEmail ? (agent.email as string) : `${agent.id}@todo-confirm-email.local`;
    const password = generatePassword();
    const passwordHash = await bcrypt.hash(password, 10);

    credentials.push({ agentId: agent.id, username, passwordHash, placeholderUsername: !hasEmail });

    lines.push(`${agent.name}`);
    lines.push(`  username: ${username}${hasEmail ? '' : '  [PLACEHOLDER — no email on record, see README]'}`);
    lines.push(`  password: ${password}`);
    lines.push('');
  }

  writeFileSync(path.join(__dirname, 'data', 'credentials.json'), JSON.stringify(credentials, null, 2));
  writeFileSync(path.join(__dirname, '..', 'seed-credentials.txt'), lines.join('\n'));

  console.log(lines.join('\n'));
  console.log(`Seeded ${credentials.length} agent accounts from live data.`);
  console.log('Plaintext credentials written once to seed-credentials.txt (gitignored). Hashes only in server/data/credentials.json.');
}

seed().catch((err) => {
  console.error('Seed failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
