import bcrypt from 'bcryptjs';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

/**
 * Seed login credentials into the Cloudflare Worker's CREDENTIALS KV namespace.
 *
 * PLACEHOLDER DECISION (per prompt section 6, still not final): username = agent's Email
 * (AssessmentDash column C, sourced live). If an agent has no email on record, a clearly flagged
 * placeholder username is generated instead so a login can still exist for testing.
 *
 * Passwords are randomly generated here and never stored in plaintext — only their bcrypt hash
 * goes into KV. The plaintext is printed once and written to seed-credentials.txt (gitignored).
 *
 * Usage:
 *   npm run seed              # writes to LOCAL wrangler KV simulation (safe default)
 *   npm run seed -- --remote  # writes to the REAL Cloudflare KV namespace (needs wrangler auth)
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, '..');
const WORKER_DIR = path.join(REPO_ROOT, 'worker');

const LIVE_DATA_URL = process.env.LIVE_DATA_URL
  ?? 'https://raw.githubusercontent.com/jayr-ai/fa-assessment-dashboard/main/data/assessments.json';

const isRemote = process.argv.includes('--remote');

interface LiveAgent {
  id: string;
  name: string;
  email: string | null;
}

function generatePassword(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
  let out = '';
  for (let i = 0; i < 10; i++) {
    out += chars[Math.floor(Math.random() * chars.length)];
  }
  return out;
}

async function loadLiveAgents(): Promise<LiveAgent[]> {
  const res = await fetch(LIVE_DATA_URL);
  if (!res.ok) {
    throw new Error(
      `Live assessment data not found at ${LIVE_DATA_URL} (HTTP ${res.status}). ` +
      'Has the Apps Script sync run yet? See APPS_SCRIPT_SETUP.md.'
    );
  }
  return res.json() as Promise<LiveAgent[]>;
}

function putKv(key: string, value: string) {
  const args = [
    'wrangler', 'kv', 'key', 'put', key, value,
    '--binding', 'CREDENTIALS',
    isRemote ? '--remote' : '--local',
  ];
  const result = spawnSync('npx', args, { cwd: WORKER_DIR, encoding: 'utf-8' });
  if (result.status !== 0) {
    throw new Error(`wrangler kv key put failed for "${key}":\n${result.stderr || result.stdout}`);
  }
}

async function seed() {
  const agents = await loadLiveAgents();

  const lines: string[] = [
    'FA Assessment Dashboard — login credentials (generated by scripts/seed.ts)',
    `Target: ${isRemote ? 'REMOTE Cloudflare KV (live)' : 'local wrangler KV simulation (dev only)'}`,
    'Do not reuse these passwords anywhere else.',
    '',
  ];

  for (const agent of agents) {
    const hasEmail = !!agent.email;
    const username = hasEmail ? (agent.email as string) : `${agent.id}@todo-confirm-email.local`;
    const password = generatePassword();
    const passwordHash = await bcrypt.hash(password, 10);

    putKv(username.toLowerCase(), JSON.stringify({ agentId: agent.id, passwordHash }));

    lines.push(`${agent.name}`);
    lines.push(`  username: ${username}${hasEmail ? '' : '  [PLACEHOLDER — no email on record, see README]'}`);
    lines.push(`  password: ${password}`);
    lines.push('');
  }

  writeFileSync(path.join(REPO_ROOT, 'seed-credentials.txt'), lines.join('\n'));

  console.log(lines.join('\n'));
  console.log(`Seeded ${agents.length} agent accounts into ${isRemote ? 'REMOTE' : 'local'} KV.`);
  console.log('Plaintext credentials written once to seed-credentials.txt (gitignored).');
}

seed().catch((err) => {
  console.error('Seed failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
